name: Deploy to Treasure Workflow

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Workflow
        uses: kawamon/treasure-workflow-actions@v1
        with:
          td_wf_endpoint: https://api-workflow.treasuredata.co.jp
          td_master_apikey: ${{ secrets.TD_MASTER_APIKEY }}
          td_wf_project_name: test_workflow_cicd
